name: abrir_pagina_web_com_selenium

jobs:
  abrir_pagina_web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar o ambiente
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          sudo apt-get install -y chromium-browser
          export CHROME_BIN=/usr/bin/chromium-browser

      - name: Executar o código
        run: |
          C://Program Files//Java//jdk-16.0.1//bin -Dwebdriver.chrome.driver=src/main/driver/chromedriver.exe -jar AtividadeExtraAutomacao.jar
