name: Acessar site http://sampleapp.tricentis.com/101/

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  access-site:
    runs-on: ubuntu-latest

    steps:
    - name: Acessar o site
      uses: appleboy/ssh-action@master
      with:
        host: sampleapp.tricentis.com
        script: |
          curl -I http://sampleapp.tricentis.com/101/
